// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: evm.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const addChain = `-- name: AddChain :one
INSERT INTO chains (name, rpcs, chain_id)
VALUES ($1, $2, $3) RETURNING id, name, rpcs, chain_id, updated_at
`

type AddChainParams struct {
	Name    string   `json:"name"`
	Rpcs    []string `json:"rpcs"`
	ChainID int64    `json:"chain_id"`
}

func (q *Queries) AddChain(ctx context.Context, arg AddChainParams) (Chain, error) {
	row := q.db.QueryRowContext(ctx, addChain, arg.Name, pq.Array(arg.Rpcs), arg.ChainID)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.Rpcs),
		&i.ChainID,
		&i.UpdatedAt,
	)
	return i, err
}

const addPrivateKey = `-- name: AddPrivateKey :one
INSERT INTO private_keys (private_key, address)
VALUES ($1, LOWER($2)) RETURNING id, private_key, address, updated_at
`

type AddPrivateKeyParams struct {
	PrivateKey string `json:"private_key"`
	Address    string `json:"address"`
}

func (q *Queries) AddPrivateKey(ctx context.Context, arg AddPrivateKeyParams) (PrivateKey, error) {
	row := q.db.QueryRowContext(ctx, addPrivateKey, arg.PrivateKey, arg.Address)
	var i PrivateKey
	err := row.Scan(
		&i.ID,
		&i.PrivateKey,
		&i.Address,
		&i.UpdatedAt,
	)
	return i, err
}

const getChain = `-- name: GetChain :one
SELECT id, name, rpcs, chain_id, updated_at
FROM chains
WHERE chain_id = $1 LIMIT 1
`

func (q *Queries) GetChain(ctx context.Context, chainID int64) (Chain, error) {
	row := q.db.QueryRowContext(ctx, getChain, chainID)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.Rpcs),
		&i.ChainID,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrivateKey = `-- name: GetPrivateKey :one
SELECT id, private_key, address, updated_at
FROM private_keys
WHERE LOWER($1) = LOWER(address) LIMIT 1
`

func (q *Queries) GetPrivateKey(ctx context.Context, address string) (PrivateKey, error) {
	row := q.db.QueryRowContext(ctx, getPrivateKey, address)
	var i PrivateKey
	err := row.Scan(
		&i.ID,
		&i.PrivateKey,
		&i.Address,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddresses = `-- name: ListAddresses :many
SELECT address
FROM private_keys
`

func (q *Queries) ListAddresses(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChains = `-- name: ListChains :many
SELECT id, name, rpcs, chain_id, updated_at
FROM chains
`

func (q *Queries) ListChains(ctx context.Context) ([]Chain, error) {
	rows, err := q.db.QueryContext(ctx, listChains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chain{}
	for rows.Next() {
		var i Chain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			pq.Array(&i.Rpcs),
			&i.ChainID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
